runs:
  using: composite

  steps:
    - name: Setup Python 3
      uses: actions/setup-python@v4
      with:
        python-version: 3.x
        cache: pip

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r ./image-generator/requirements.txt
      shell: bash # Composite jobs must specify the shell.
