name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node

      - name: Check formatting with Prettier
        run: npx prettier --log-level=warn --check .

  python_format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-python

      - name: Check Python formatting with Black
        uses: lgeiger/black-action@master
        with:
          args: --check .

  website_build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node
      - uses: ./.github/workflows/setup-python

      - name: Use Docusaurus to build the website
        run: bash build.sh

      - name: Deploy to GitHub pages
        if: github.ref == 'refs/heads/master' && needs.pr-check.outputs.number != 'null'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build

  typescript:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node

      - name: Use TypeScript to type-check the website
        run: npx tsc --noEmit

  eslint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node

      - name: Use ESLint to lint the website
        run: npx eslint --max-warnings 0 .

  remark:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node

      - name: Use Remark to lint the Markdown
        run: npx remark --quiet --frail docs misc

  cspell:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-node

      - name: Use CSpell to spell check everything
        run: |
          npx cspell --no-progress --no-summary .
          npx cspell-check-unused-words

  yaml:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/workflows/setup-python

      - name: Check that YAML files are valid
        run: bash "./image-generator/check_valid.sh"

      - name: Check for unused YAML files
        run: python "./image-generator/check_unused.py"

  discord:
    name: Discord Failure Notification
    needs:
      [
        format,
        python_format,
        website_build,
        typescript,
        eslint,
        remark,
        cspell,
        yaml,
      ]
    # "always()" is needed to always run this job, even if the other jobs fail.
    # We don't want to spam the "#conventions-new" channel when people have failing pull requests.
    if: always() && github.ref == 'refs/heads/master' && github.event_name != 'pull_request'
    runs-on: ubuntu-latest
    steps:
      - uses: technote-space/workflow-conclusion-action@v2
      - if: env.WORKFLOW_CONCLUSION != 'cancelled'
        uses: sarisia/actions-status-discord@v1
        with:
          webhook: ${{ secrets.DISCORD_WEBHOOK }}
          status: ${{ env.WORKFLOW_CONCLUSION }}
          title: "Webpage Deploy"
          content: <@&1102638373040029778>
